"""add_profile_image_to_users

Revision ID: b670d8cd4f69
Revises: 9065613c8e08
Create Date: 2025-05-17 22:13:58.993268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b670d8cd4f69'
down_revision: Union[str, None] = '9065613c8e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'section',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('profile_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.alter_column('students', 'section',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
